name: Release Studio 0.2 UI Image
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  release-studio-ui:
    if: github.repository_owner == 'Apicurio'
    runs-on: ubuntu-latest
    steps:
        # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

        # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Checkout Source Code
        run: |
          git clone -b master --single-branch https://github.com/Apicurio/apicurio-studio.git studio

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Project
        run: cd studio && mvn clean install -Pprod

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and Publish Studio UI
        uses: docker/build-push-action@v2
        with:
         context: ./studio/platforms/quarkus/ui
         file: ./studio/platforms/quarkus/ui/Dockerfile
         platforms: ${{env.PLATFORMS}}
         push: true
         tags: |
           docker.io/apicurio/apicurio-studio-ui:${{ github.event.inputs.release-version }}
           quay.io/apicurio/apicurio-studio-ui:${{ github.event.inputs.release-version }}

      - name: Google Chat Notification
        if: ${{ failure() }}
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.job }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}